- name: Install NodeJS and Git
  hosts: jenkins-servers
  become: True
  tasks:
    - name: update apt package manager repositories
      apt: update_cache=yes

    - name: install node 
      shell: |
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs

    - name: install git 
      apt: name=git update_cache=yes
