- name: Install Jenkins
  hosts: jenkins-servers
  become: True
  tasks:
    - name: Install the Jenkins apt repository key
      apt_key: url=https://pkg.jenkins.io/debian-stable/jenkins.io.key state=present

    - name: Configure the repository
      apt_repository: repo='deb https://pkg.jenkins.io/debian-stable binary/' state=present

    - name: update apt package manager repositories
      apt: update_cache=yes

    - name: Install Jenkins
      apt: name=jenkins update_cache=yes

    - name: Start up Jenkins
      service: name=jenkins state=started